"""empty message

Revision ID: 05e8296bb915
Revises: 739b00fa934c
Create Date: 2019-03-12 18:30:20.820199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05e8296bb915'
down_revision = '739b00fa934c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pwd', sa.String(length=80), nullable=True))
    op.drop_column('user', 'hashpw')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', mysql.VARCHAR(length=15), nullable=True))
    op.add_column('user', sa.Column('hashpw', mysql.VARCHAR(length=80), nullable=True))
    op.drop_column('user', 'pwd')
    # ### end Alembic commands ###
