"""empty message

Revision ID: 0c6ad2488134
Revises: c66d171d1988
Create Date: 2019-03-16 10:16:24.670401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6ad2488134'
down_revision = 'c66d171d1988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('comentario', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'comentario')
    # ### end Alembic commands ###
