"""empty message

Revision ID: 4fb1dbb77e88
Revises: 5456cf416774
Create Date: 2019-06-08 17:00:31.598965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb1dbb77e88'
down_revision = '5456cf416774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.Column('frontendVersion', sa.String(length=10), nullable=True),
    sa.Column('backendVersion', sa.String(length=10), nullable=True),
    sa.Column('python_code', sa.String(length=25000), nullable=True),
    sa.Column('n_input_ports', sa.Integer(), nullable=True),
    sa.Column('n_output_ports', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actor')
    # ### end Alembic commands ###
