"""empty message

Revision ID: 879b7af95652
Revises: 9892ef7aff16
Create Date: 2019-06-12 00:42:36.360588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879b7af95652'
down_revision = '9892ef7aff16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=280), nullable=True),
    sa.Column('comercial_name', sa.String(length=280), nullable=True),
    sa.Column('logo', sa.String(length=1000), nullable=True),
    sa.Column('cif', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=10), nullable=True),
    sa.Column('admin_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    # ### end Alembic commands ###
