"""empty message

Revision ID: 9a956aa63d1f
Revises: e31b148c93b5
Create Date: 2019-06-20 18:58:22.000007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a956aa63d1f'
down_revision = 'e31b148c93b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('aws_key', sa.String(length=255), nullable=True))
    op.add_column('company', sa.Column('aws_secret', sa.String(length=255), nullable=True))
    op.add_column('project', sa.Column('machine_ami_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'machine_ami_id')
    op.drop_column('company', 'aws_secret')
    op.drop_column('company', 'aws_key')
    # ### end Alembic commands ###
