"""empty message

Revision ID: 9f2dade7275f
Revises: 033ccd3f83ba
Create Date: 2019-06-25 20:07:15.747010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2dade7275f'
down_revision = '033ccd3f83ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status__project', sa.Column('error', sa.String(length=10000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status__project', 'error')
    # ### end Alembic commands ###
