"""empty message

Revision ID: c0c91e8a8cef
Revises: 05e8296bb915
Create Date: 2019-03-13 20:00:17.696434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0c91e8a8cef'
down_revision = '05e8296bb915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstName', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('lastName', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=True))
    # op.drop_index('email', table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'name')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=30), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('email', 'user', ['email'], unique=True)
    op.drop_column('user', 'username')
    op.drop_column('user', 'lastName')
    op.drop_column('user', 'firstName')
    # ### end Alembic commands ###
