version: '3.5'
services:
 backend:
  build: .
  ports:
   - "8081:8081"
  environment:
   - PORT=8081
   - FLASK_APP=mlpython
   - FLASK_DEBUG=true
  depends_on:
   - mysql_db
 
 mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mambadb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'mambaml'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'mambaml'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'mambaml'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
