# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
FROM localhost:5000/myweb as build-stage

WORKDIR /app

COPY package*.json /app/

RUN apt-get update -y && \
    apt-get install -y npm

RUN npm install

COPY ./ /app/

ARG configuration=production

RUN npm run build -- --output-path=./dist/out --configuration $configuration

# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:1.15

COPY --from=build-stage /app/dist/out/ /usr/share/nginx/html

# Copy the default nginx.conf provided by tiangolo/node-frontend
COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf


